# Generated by Django 4.2.13 on 2025-09-18 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_text_es", models.CharField(max_length=255)),
                ("back_text_gn", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("suspended", models.BooleanField(default=False)),
                ("ai_difficulty", models.FloatField(default=0.0)),
                ("half_life_days", models.FloatField(default=1.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SRSDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Mi Glosario", max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AlterField(
            model_name="fillblankexercise",
            name="prompt_text",
            field=models.TextField(
                help_text="Usa '____' para indicar el espacio en blanco."
            ),
        ),
        migrations.AlterField(
            model_name="matchingexercise",
            name="instructions",
            field=models.CharField(default="Relaciona las parejas", max_length=255),
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("interval_before", models.PositiveIntegerField(default=0)),
                ("interval_after", models.PositiveIntegerField(default=0)),
                ("ef_before", models.FloatField(default=2.5)),
                ("ef_after", models.FloatField(default=2.5)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="learning.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="learning.srsdeck",
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SRSUserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theta", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="learning.srsdeck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "deck")},
            },
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["user", "deck", "due_at"], name="learning_fl_user_id_b0b590_idx"
            ),
        ),
    ]
