# Generated by Django 4.2.13 on 2025-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_flashcard_srsdeck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="srsuserstate",
            name="mode",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("comfortable", "Comfortable"),
                    ("aggressive", "Aggressive"),
                ],
                default="comfortable",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="srsuserstate",
            name="new_limit",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="srsuserstate",
            name="new_shown_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="srsuserstate",
            name="new_shown_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
