# Generated by Django 4.2.13 on 2025-09-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_srsuserstate_mode_srsuserstate_new_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('es_gn', 'Español → Guaraní'), ('gn_es', 'Guaraní → Español')], default='es_gn', max_length=10)),
                ('acceptable_answers', models.JSONField(default=list, help_text='Lista de respuestas válidas/sinónimos')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(blank=True, default='', max_length=255)),
                ('audio', models.FileField(help_text='Audio estímulo (mp3/wav)', upload_to='listening/')),
                ('choices_json', models.JSONField(help_text='[{"key":"A","text":"..."}, ...]')),
                ('correct_key', models.CharField(max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listenings', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DragDropExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(help_text='Ej: Ordena la oración.', max_length=255)),
                ('correct_tokens', models.JSONField(help_text="Lista de tokens en orden correcto, p.ej. ['Che','héra','María']")),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragdrops', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
