# Generated by Django 4.2.13 on 2025-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_translationexercise_listeningexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryentry',
            name='audio_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='glossary_audio/'),
        ),
    ]
