# Generated by Django 4.2.13 on 2025-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_achievement_dailychallenge_leaderboard_virtualpet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryentry',
            name='category',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='mastery_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='usage_examples',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
