# Generated by Django 4.2.13 on 2025-10-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_enhance_glossary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'ordering': ['-is_favorite', '-last_reviewed', '-created_at']},
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='correct_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='custom_reminder_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='incorrect_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='pronunciation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='pronunciation_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='reminder_frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('every_3_days', 'Cada 3 días'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('custom', 'Personalizado')], default='every_3_days', max_length=20),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='study_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='total_study_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='glossaryentry',
            index=models.Index(fields=['user', 'category'], name='learning_gl_user_id_0509f0_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryentry',
            index=models.Index(fields=['user', 'difficulty'], name='learning_gl_user_id_ba9168_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryentry',
            index=models.Index(fields=['user', 'is_favorite'], name='learning_gl_user_id_e718d6_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryentry',
            index=models.Index(fields=['user', 'next_review_date'], name='learning_gl_user_id_403c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryentry',
            index=models.Index(fields=['is_public', 'is_verified'], name='learning_gl_is_publ_37244b_idx'),
        ),
    ]
