# Generated by Django 4.2.13 on 2025-10-06 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0008_add_glossary_fields_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título de la conversación (opcional)', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(blank=True, help_text='Mensaje del usuario')),
                ('bot_response_guarani', models.TextField(blank=True, help_text='Respuesta del bot en guaraní')),
                ('bot_response_spanish', models.TextField(blank=True, help_text='Traducción al español')),
                ('explanation', models.TextField(blank=True, help_text='Explicación adicional')),
                ('new_words', models.JSONField(blank=True, default=list, help_text='Nuevas palabras aprendidas')),
                ('model_used', models.CharField(default='deepseek', help_text='Modelo de IA utilizado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
